// <auto-generated />
using System;
using Kanini.LMP.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kanini.LMP.Data.Migrations
{
    [DbContext(typeof(LmpDbContext))]
    [Migration("20251204074458_UpdateUserAndLoanApplicationFlow")]
    partial class UpdateUserAndLoanApplicationFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AadhaarNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CreditScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("HomeOwnershipStatus")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PANNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte[]>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            AadhaarNumber = "123456789012",
                            AnnualIncome = 1200000m,
                            CreditScore = 750m,
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            Gender = 0,
                            HomeOwnershipStatus = 1,
                            Occupation = "Software Engineer",
                            PANNumber = "ABCDE1234F",
                            PhoneNumber = "9876543210",
                            ProfileImage = new byte[] { 1 },
                            UserId = 2
                        },
                        new
                        {
                            CustomerId = 2,
                            AadhaarNumber = "123456789013",
                            AnnualIncome = 2000000m,
                            CreditScore = 800m,
                            DateOfBirth = new DateOnly(1985, 5, 15),
                            Gender = 1,
                            HomeOwnershipStatus = 0,
                            Occupation = "Business Owner",
                            PANNumber = "ABCDE1234G",
                            PhoneNumber = "9876543211",
                            ProfileImage = new byte[] { 2 },
                            UserId = 3
                        },
                        new
                        {
                            CustomerId = 3,
                            AadhaarNumber = "123456789014",
                            AnnualIncome = 1800000m,
                            CreditScore = 780m,
                            DateOfBirth = new DateOnly(1995, 10, 20),
                            Gender = 0,
                            HomeOwnershipStatus = 1,
                            Occupation = "Doctor",
                            PANNumber = "ABCDE1234H",
                            PhoneNumber = "9876543212",
                            ProfileImage = new byte[] { 3 },
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.EMIPlan", b =>
                {
                    b.Property<int>("EMIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMIId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyEMI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipleAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RateOfInterest")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalInterestPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRepaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EMIId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoanApplicationBaseId");

                    b.ToTable("EMIPlans");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", b =>
                {
                    b.Property<int>("LoanApplicationBaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanApplicationBaseId"));

                    b.Property<DateOnly?>("ApprovedDate")
                        .HasColumnType("date");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoanProductType")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SubmissionDate")
                        .HasColumnType("date");

                    b.HasKey("LoanApplicationBaseId");

                    b.HasIndex("CustomerId");

                    b.ToTable("LoanApplicationBases", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.LoanApplicant", b =>
                {
                    b.Property<int>("LoanApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanApplicantId"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApplicantRole")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.HasKey("LoanApplicantId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoanApplicationBaseId");

                    b.ToTable("LoanApplicants");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.AddressInformation", b =>
                {
                    b.Property<int>("AddressInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressInformationId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("MobileNumber1")
                        .HasColumnType("int");

                    b.Property<int>("MobileNumber2")
                        .HasColumnType("int");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PresentAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AddressInformationId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("AddressInformations");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.Declaration", b =>
                {
                    b.Property<int>("DeclarationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeclarationId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("DeclarationId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("Declarations");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.DocumentUpload", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<byte[]>("DocumentData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DocumentUploads");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.FamilyEmergencyDetails", b =>
                {
                    b.Property<int>("FamilyEmergencyDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FamilyEmergencyDetailsId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("MobileNumber")
                        .HasColumnType("int");

                    b.Property<string>("RelationshipWithApplicant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FamilyEmergencyDetailsId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("FamilyEmergencyDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.LoanDetails", b =>
                {
                    b.Property<int>("LoanDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanDetailsId"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("LoanApplicationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MonthlyInstallment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("LoanDetailsId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.PersonalDetails", b =>
                {
                    b.Property<int>("PersonalDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalDetailsId"));

                    b.Property<string>("CountryOfBirth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DistrictOfBirth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EducationQualification")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<byte[]>("IDProofImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<string>("PANNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ResidentialStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("SignatureImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PersonalDetailsId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.HomeLoanEntities.PropertyDetails", b =>
                {
                    b.Property<int>("PropertyDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyDetailsId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("int");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PropertyDetailsId");

                    b.HasIndex("LoanApplicationBaseId");

                    b.ToTable("PropertyDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.LoanProduct", b =>
                {
                    b.Property<int>("LoanProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanProductId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoanType")
                        .HasColumnType("int");

                    b.HasKey("LoanProductId");

                    b.HasIndex("LoanType")
                        .IsUnique();

                    b.ToTable("LoanProducts");

                    b.HasData(
                        new
                        {
                            LoanProductId = 1,
                            IsActive = true,
                            LoanType = 1
                        },
                        new
                        {
                            LoanProductId = 2,
                            IsActive = true,
                            LoanType = 2
                        },
                        new
                        {
                            LoanProductId = 3,
                            IsActive = true,
                            LoanType = 3
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.VehicleLoanEntities.VehicleInformation", b =>
                {
                    b.Property<int>("VehicleInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleInformationId"));

                    b.Property<decimal>("ExShowroomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Variant")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleCondition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleInformationId");

                    b.HasIndex("LoanApplicationBaseId");

                    b.ToTable("VehicleInformations");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.ManagerEntities.LoanAccount", b =>
                {
                    b.Property<int>("LoanAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanAccountId"));

                    b.Property<int>("CurrentPaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DaysPastDue")
                        .HasColumnType("int");

                    b.Property<DateTime>("DisbursementDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastStatusUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrincipalRemaining")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLateFeePaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaidInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaidPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LoanAccountId");

                    b.ToTable("LoanAccounts");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.ManagerEntities.LoanOriginationWorkflow", b =>
                {
                    b.Property<int>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowId"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StepName")
                        .HasColumnType("int");

                    b.Property<int>("StepStatus")
                        .HasColumnType("int");

                    b.HasKey("WorkflowId");

                    b.ToTable("LoanOriginationWorkflows");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EMIId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoanAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@gmail.com",
                            FullName = "Manager One",
                            PasswordHash = "hashedpassword",
                            Roles = 1,
                            Status = 1
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer1@gmail.com",
                            FullName = "Customer One",
                            PasswordHash = "hashedpassword",
                            Roles = 0,
                            Status = 1
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer2@gmail.com",
                            FullName = "Customer Two",
                            PasswordHash = "hashedpassword",
                            Roles = 0,
                            Status = 1
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer3@gmail.com",
                            FullName = "Customer Three",
                            PasswordHash = "hashedpassword",
                            Roles = 0,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", b =>
                {
                    b.HasBaseType("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase");

                    b.Property<string>("BuilderContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BuilderEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BuilderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BuilderRegistrationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("LoanPurpose")
                        .HasColumnType("int");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("PropertyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<decimal>("RequestedLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.ToTable("HomeLoanApplications", (string)null);
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.PersonalLoanApplication", b =>
                {
                    b.HasBaseType("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("LoanPurpose")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OfficeAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("RequestedLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.Property<int>("WorkExperienceYears")
                        .HasColumnType("int");

                    b.ToTable("PersonalLoanApplications", (string)null);
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", b =>
                {
                    b.HasBaseType("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase");

                    b.Property<string>("DealerAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DealerContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DealerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DealerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExShowroomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("LoanPurposeVehicle")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("OnRoadPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RequestedLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.ToTable("VehicleLoanApplications", (string)null);
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.Customer", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.CustomerEntities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.EMIPlan", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", "LoanApplicationBase")
                        .WithMany()
                        .HasForeignKey("LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LoanApplicationBase");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.Customer", "Customer")
                        .WithMany("LoanApplications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.LoanApplicant", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", "LoanApplicationBase")
                        .WithMany("Applicants")
                        .HasForeignKey("LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LoanApplicationBase");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.AddressInformation", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("AddressInformation")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.AddressInformation", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.Declaration", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("Declaration")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.Declaration", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.DocumentUpload", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("DocumentUpload")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.DocumentUpload", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanini.LMP.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.FamilyEmergencyDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("FamilyEmergencyDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.FamilyEmergencyDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.LoanDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("LoanDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.LoanDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.PersonalDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("PersonalDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.PersonalDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.HomeLoanEntities.PropertyDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", "LoanApplicationBase")
                        .WithMany()
                        .HasForeignKey("LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoanApplicationBase");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.VehicleLoanEntities.VehicleInformation", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", "LoanApplicationBase")
                        .WithMany()
                        .HasForeignKey("LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoanApplicationBase");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.Notification", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanini.LMP.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.PersonalLoanApplication", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanApplicationEntites.PersonalLoanApplication", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.Customer", b =>
                {
                    b.Navigation("LoanApplications");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", b =>
                {
                    b.Navigation("AddressInformation")
                        .IsRequired();

                    b.Navigation("Applicants");

                    b.Navigation("Declaration")
                        .IsRequired();

                    b.Navigation("DocumentUpload")
                        .IsRequired();

                    b.Navigation("FamilyEmergencyDetails")
                        .IsRequired();

                    b.Navigation("LoanDetails")
                        .IsRequired();

                    b.Navigation("PersonalDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
