// <auto-generated />
using System;
using Kanini.LMP.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kanini.LMP.Data.Migrations
{
    [DbContext(typeof(LmpDbContext))]
    [Migration("20251202072356_AddNotificationPreferences")]
    partial class AddNotificationPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CreditScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("HomeOwnershipStatus")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte[]>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            AnnualIncome = 1500000.00m,
                            CreditScore = 780m,
                            DateOfBirth = new DateOnly(1995, 10, 20),
                            Gender = 0,
                            HomeOwnershipStatus = 1,
                            Occupation = "Software Engineer",
                            PhoneNumber = "9876543210",
                            ProfileImage = new byte[] { 222, 173, 190, 239 },
                            UpdatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            CustomerId = 2,
                            AnnualIncome = 950000.00m,
                            CreditScore = 725m,
                            DateOfBirth = new DateOnly(1998, 5, 15),
                            Gender = 1,
                            HomeOwnershipStatus = 0,
                            Occupation = "Data Analyst",
                            PhoneNumber = "8012345678",
                            ProfileImage = new byte[] { 222, 173, 190, 239 },
                            UpdatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.EMIPlan", b =>
                {
                    b.Property<int>("EMIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMIId"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoanAccountId")
                        .HasColumnType("int");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyEMI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipleAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RateOfInterest")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalInterestPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRepaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EMIId");

                    b.HasIndex("LoanAccountId");

                    b.ToTable("EMIPlans");

                    b.HasData(
                        new
                        {
                            EMIId = 1,
                            IsCompleted = false,
                            LoanAccountId = 1,
                            LoanApplicationBaseId = 1,
                            MonthlyEMI = 11122.22m,
                            PrincipleAmount = 500000.00m,
                            RateOfInterest = 12.00m,
                            Status = 0,
                            TermMonths = 60,
                            TotalInterestPaid = 167333.20m,
                            TotalRepaymentAmount = 667333.20m
                        },
                        new
                        {
                            EMIId = 2,
                            IsCompleted = true,
                            LoanAccountId = 2,
                            LoanApplicationBaseId = 2,
                            MonthlyEMI = 4403.95m,
                            PrincipleAmount = 50000.00m,
                            RateOfInterest = 10.00m,
                            Status = 2,
                            TermMonths = 12,
                            TotalInterestPaid = 2847.40m,
                            TotalRepaymentAmount = 52847.40m
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.JunctionTable.ApplicationDocumentLink", b =>
                {
                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentRequirementType")
                        .HasColumnType("int");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.HasKey("LoanApplicationBaseId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("ApplicationDocumentLinks");

                    b.HasData(
                        new
                        {
                            LoanApplicationBaseId = 1,
                            DocumentId = 1,
                            DocumentRequirementType = 6,
                            LinkedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            LoanApplicationBaseId = 2,
                            DocumentId = 2,
                            DocumentRequirementType = 6,
                            LinkedAt = new DateTime(2025, 10, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.JunctionTable.LoanApplicant", b =>
                {
                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApplicantRole")
                        .HasColumnType("int");

                    b.HasKey("LoanApplicationBaseId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("LoanApplicants");

                    b.HasData(
                        new
                        {
                            LoanApplicationBaseId = 1,
                            CustomerId = 1,
                            AddedDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApplicantRole = 0
                        },
                        new
                        {
                            LoanApplicationBaseId = 1,
                            CustomerId = 2,
                            AddedDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApplicantRole = 1
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", b =>
                {
                    b.Property<int>("LoanApplicationBaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanApplicationBaseId"));

                    b.Property<DateOnly?>("ApprovedDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoanProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SubmissionDate")
                        .HasColumnType("date");

                    b.HasKey("LoanApplicationBaseId");

                    b.HasIndex("LoanProductType");

                    b.ToTable("LoanApplicationBases", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.AddressInformation", b =>
                {
                    b.Property<int>("AddressInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressInformationId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("MobileNumber1")
                        .HasColumnType("int");

                    b.Property<int>("MobileNumber2")
                        .HasColumnType("int");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PresentAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AddressInformationId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("AddressInformations");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.Declaration", b =>
                {
                    b.Property<int>("DeclarationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeclarationId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("DeclarationId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("Declarations");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.DocumentUpload", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<byte[]>("DocumentData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentUploads");

                    b.HasData(
                        new
                        {
                            DocumentId = 1,
                            DocumentData = new byte[] { 85, 84, 73, 76 },
                            DocumentName = "Electricity Bill Jan 2025",
                            DocumentType = "AddressProof",
                            LoanApplicationBaseId = 1,
                            UploadedAt = new DateTime(2025, 1, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            DocumentId = 2,
                            DocumentData = new byte[] { 80, 65, 89, 83 },
                            DocumentName = "Pay Stub October 2025",
                            DocumentType = "IncomeProof",
                            LoanApplicationBaseId = 2,
                            UploadedAt = new DateTime(2025, 10, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.FamilyEmergencyDetails", b =>
                {
                    b.Property<int>("FamilyEmergencyDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FamilyEmergencyDetailsId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("MobileNumber")
                        .HasColumnType("int");

                    b.Property<string>("RelationshipWithApplicant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FamilyEmergencyDetailsId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("FamilyEmergencyDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.LoanDetails", b =>
                {
                    b.Property<int>("LoanDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanDetailsId"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("LoanApplicationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MonthlyInstallment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("LoanDetailsId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("LoanDetails");

                    b.HasData(
                        new
                        {
                            LoanDetailsId = 1,
                            AppliedDate = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            InterestRate = 12.00m,
                            LoanApplicationBaseId = 1,
                            LoanApplicationId = 0,
                            MonthlyInstallment = 11122.22m,
                            RequestedAmount = 500000.00m,
                            TenureMonths = 60
                        },
                        new
                        {
                            LoanDetailsId = 2,
                            AppliedDate = new DateTime(2025, 10, 20, 15, 30, 0, 0, DateTimeKind.Utc),
                            InterestRate = 10.00m,
                            LoanApplicationBaseId = 2,
                            LoanApplicationId = 0,
                            MonthlyInstallment = 4403.95m,
                            RequestedAmount = 50000.00m,
                            TenureMonths = 12
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.PersonalDetails", b =>
                {
                    b.Property<int>("PersonalDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalDetailsId"));

                    b.Property<string>("CountryOfBirth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DistrictOfBirth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EducationQualification")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<byte[]>("IDProofImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<string>("PANNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ResidentialStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("SignatureImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PersonalDetailsId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.HomeLoanEntities.BuilderInformation", b =>
                {
                    b.Property<int>("BuilderInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuilderInformationId"));

                    b.Property<string>("BuilderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BuilderRegistrationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BuilderInformationId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("BuilderInformations");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.HomeLoanEntities.HomeLoanDetails", b =>
                {
                    b.Property<int>("HomeLoanDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeLoanDetailsId"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("LoanApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("LoanPurpose")
                        .HasColumnType("int");

                    b.Property<decimal>("PropertyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RequestedLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("HomeLoanDetailsId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("HomeLoanDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.HomeLoanEntities.PropertyDetails", b =>
                {
                    b.Property<int>("PropertyDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyDetailsId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("int");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("PropertyDetailsId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("PropertyDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.LoanProduct", b =>
                {
                    b.Property<int>("LoanProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanProductId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoanProductDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoanProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LoanProductId");

                    b.HasIndex("LoanProductName")
                        .IsUnique();

                    b.ToTable("LoanProducts");

                    b.HasData(
                        new
                        {
                            LoanProductId = 1,
                            IsActive = true,
                            LoanProductDescription = "Unsecured loan for personal use, high flexibility, terms up to 7 years.",
                            LoanProductName = "PersonalLoan-Standard"
                        },
                        new
                        {
                            LoanProductId = 2,
                            IsActive = true,
                            LoanProductDescription = "Secured loan for pre-owned vehicles, up to 90% financing, maximum term 5 years.",
                            LoanProductName = "CarLoan-Used"
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.PersonalLoanEntities.EmploymentDetails", b =>
                {
                    b.Property<int>("EmploymentDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmploymentDetailsId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int?>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<string>("OfficeAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmploymentDetailsId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique()
                        .HasFilter("[LoanApplicationBaseId] IS NOT NULL");

                    b.ToTable("EmploymentDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.PersonalLoanEntities.FinancialInformation", b =>
                {
                    b.Property<int>("FinancialInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinancialInformationId"));

                    b.Property<int>("Education")
                        .HasColumnType("int");

                    b.Property<int>("ExpenseOther")
                        .HasColumnType("int");

                    b.Property<int>("FoodandClothing")
                        .HasColumnType("int");

                    b.Property<int?>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("LoanRepayment")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryOther")
                        .HasColumnType("int");

                    b.Property<int>("Rent")
                        .HasColumnType("int");

                    b.Property<int>("RentandUtility")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FinancialInformationId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique()
                        .HasFilter("[LoanApplicationBaseId] IS NOT NULL");

                    b.ToTable("FinancialInformations");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.VehicleLoanEntities.DealerInformation", b =>
                {
                    b.Property<int>("DealerInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DealerInformationId"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DealerAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DealerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DealerInformationId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("DealerInformations");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.VehicleLoanEntities.VehicleInformation", b =>
                {
                    b.Property<int>("VehicleInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleInformationId"));

                    b.Property<decimal>("ExShowroomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VehicleCondition")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("VehicleInformationId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("VehicleInformations");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.VehicleLoanEntities.VehicleLoanDetails", b =>
                {
                    b.Property<int>("VehicleLoanDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleLoanDetailsId"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("LoanApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("LoanPurposeVehicle")
                        .HasColumnType("int");

                    b.Property<decimal>("OnRoadPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RequestedLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("VehicleLoanDetailsId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("VehicleLoanDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.ManagerEntities.LoanAccount", b =>
                {
                    b.Property<int>("LoanAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanAccountId"));

                    b.Property<int>("CurrentPaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DaysPastDue")
                        .HasColumnType("int");

                    b.Property<DateTime>("DisbursementDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastStatusUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrincipalRemaining")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLateFeePaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaidInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaidPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LoanAccountId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("LoanAccounts");

                    b.HasData(
                        new
                        {
                            LoanAccountId = 1,
                            CurrentPaymentStatus = 0,
                            CustomerId = 1,
                            DaysPastDue = 0,
                            DisbursementDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastPaymentDate = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastStatusUpdate = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanApplicationBaseId = 1,
                            PrincipalRemaining = 350000.00m,
                            TotalLateFeePaidAmount = 0.00m,
                            TotalLoanAmount = 500000.00m,
                            TotalPaidInterest = 45000.00m,
                            TotalPaidPrincipal = 150000.00m
                        },
                        new
                        {
                            LoanAccountId = 2,
                            CurrentPaymentStatus = 6,
                            CustomerId = 2,
                            DaysPastDue = 0,
                            DisbursementDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastPaymentDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastStatusUpdate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanApplicationBaseId = 2,
                            PrincipalRemaining = 0.00m,
                            TotalLateFeePaidAmount = 150.00m,
                            TotalLoanAmount = 50000.00m,
                            TotalPaidInterest = 2847.40m,
                            TotalPaidPrincipal = 50000.00m
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.ManagerEntities.LoanOriginationWorkflow", b =>
                {
                    b.Property<int>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowId"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StepName")
                        .HasColumnType("int");

                    b.Property<int>("StepStatus")
                        .HasColumnType("int");

                    b.HasKey("WorkflowId");

                    b.HasIndex("LoanApplicationBaseId");

                    b.ToTable("LoanOriginationWorkflows");

                    b.HasData(
                        new
                        {
                            WorkflowId = 1,
                            CompletionDate = new DateTime(2025, 1, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            LoanApplicationBaseId = 1,
                            ManagerId = 3,
                            ManagerNotes = "Approved with standard rate.",
                            StepName = 1,
                            StepStatus = 0
                        },
                        new
                        {
                            WorkflowId = 2,
                            LoanApplicationBaseId = 2,
                            ManagerId = 4,
                            ManagerNotes = "Awaiting verification report.",
                            StepName = 2,
                            StepStatus = 3
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            Channel = 4,
                            CreatedAt = new DateTime(2025, 2, 2, 9, 30, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            IsSent = false,
                            Message = "Your Personal Loan application has been approved and funds have been disbursed to your account.",
                            Priority = 1,
                            Title = "Loan Disbursed Successfully",
                            Type = 8,
                            UserId = 1
                        },
                        new
                        {
                            NotificationId = 2,
                            Channel = 4,
                            CreatedAt = new DateTime(2025, 10, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            IsSent = false,
                            Message = "A payment of ₹4,403.95 is due in 5 days for your Car Loan.",
                            Priority = 1,
                            Title = "Payment Due Reminder",
                            Type = 8,
                            UserId = 2
                        },
                        new
                        {
                            NotificationId = 3,
                            Channel = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            IsSent = false,
                            Message = "Thank you for registering with our loan management system.",
                            Priority = 1,
                            Title = "Welcome to Loan Management Portal",
                            Type = 8,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.NotificationPreference", b =>
                {
                    b.Property<int>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreferenceId"));

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("InAppEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("SMSEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("WhatsAppEnabled")
                        .HasColumnType("bit");

                    b.HasKey("PreferenceId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EMIId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoanAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("EMIId");

                    b.ToTable("PaymentTransactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Amount = 11122.22m,
                            CreatedAt = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMIId = 1,
                            IsActive = true,
                            LoanAccountId = 1,
                            PaymentDate = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = 0,
                            Status = 1,
                            TransactionReference = "UPI-TXN-1234567890"
                        },
                        new
                        {
                            TransactionId = 2,
                            Amount = 11122.22m,
                            CreatedAt = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMIId = 1,
                            IsActive = true,
                            LoanAccountId = 1,
                            PaymentDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = 1,
                            Status = 2,
                            TransactionReference = "NB-TXN-0987654321"
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alex.johnson@customer.com",
                            FullName = "Alex Johnson",
                            PasswordHash = "hashedpassword_alex",
                            Roles = 0,
                            Status = 0
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 10, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emma.brown@customer.com",
                            FullName = "Emma Brown",
                            PasswordHash = "hashedpassword_emma",
                            Roles = 0,
                            Status = 0
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.smith@manager.com",
                            FullName = "Alice Smith (Credit)",
                            PasswordHash = "hashedpassword_alice",
                            Roles = 1,
                            Status = 0
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 2, 20, 9, 30, 0, 0, DateTimeKind.Utc),
                            Email = "bob.davis@manager.com",
                            FullName = "Bob Davis (Verification)",
                            PasswordHash = "hashedpassword_bob",
                            Roles = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", b =>
                {
                    b.HasBaseType("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase");

                    b.ToTable("HomeLoanApplications", (string)null);
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.PersonalLoanApplication", b =>
                {
                    b.HasBaseType("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase");

                    b.ToTable("PersonalLoanApplications", (string)null);

                    b.HasData(
                        new
                        {
                            LoanApplicationBaseId = 1,
                            ApprovedDate = new DateOnly(2025, 1, 25),
                            IsActive = true,
                            LoanProductType = "PersonalLoan-Standard",
                            Status = 4,
                            SubmissionDate = new DateOnly(2025, 1, 15)
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", b =>
                {
                    b.HasBaseType("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase");

                    b.ToTable("VehicleLoanApplications", (string)null);

                    b.HasData(
                        new
                        {
                            LoanApplicationBaseId = 2,
                            IsActive = true,
                            LoanProductType = "CarLoan-Used",
                            Status = 1,
                            SubmissionDate = new DateOnly(2025, 10, 20)
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.Customer", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.CustomerEntities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.EMIPlan", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.ManagerEntities.LoanAccount", null)
                        .WithMany()
                        .HasForeignKey("LoanAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.JunctionTable.ApplicationDocumentLink", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.DocumentUpload", "DocumentUpload")
                        .WithMany("ApplicationLinks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", "LoanApplicationBase")
                        .WithMany("DocumentLinks")
                        .HasForeignKey("LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentUpload");

                    b.Navigation("LoanApplicationBase");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.JunctionTable.LoanApplicant", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.Customer", "Customer")
                        .WithMany("Applications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", "LoanApplicationBase")
                        .WithMany("Applicants")
                        .HasForeignKey("LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LoanApplicationBase");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.LoanProductEntities.LoanProduct", null)
                        .WithMany()
                        .HasForeignKey("LoanProductType")
                        .HasPrincipalKey("LoanProductName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.AddressInformation", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("AddressInformation")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.AddressInformation", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.Declaration", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("Declaration")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.Declaration", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.DocumentUpload", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.FamilyEmergencyDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("FamilyEmergencyDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.FamilyEmergencyDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.LoanDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("LoanDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.LoanDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.PersonalDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("PersonalDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.PersonalDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.HomeLoanEntities.BuilderInformation", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", null)
                        .WithOne("BuilderInformation")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.HomeLoanEntities.BuilderInformation", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.HomeLoanEntities.HomeLoanDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", null)
                        .WithOne("HomeLoanDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.HomeLoanEntities.HomeLoanDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.HomeLoanEntities.PropertyDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", null)
                        .WithOne("PropertyDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.HomeLoanEntities.PropertyDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.PersonalLoanEntities.EmploymentDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("EmploymentDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.PersonalLoanEntities.EmploymentDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.PersonalLoanEntities.FinancialInformation", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne("FinancialInformation")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.PersonalLoanEntities.FinancialInformation", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.VehicleLoanEntities.DealerInformation", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", null)
                        .WithOne("DealerInformation")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.VehicleLoanEntities.DealerInformation", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.VehicleLoanEntities.VehicleInformation", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", null)
                        .WithOne("VehicleInformation")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.VehicleLoanEntities.VehicleInformation", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.VehicleLoanEntities.VehicleLoanDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", null)
                        .WithOne("VehicleLoanDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.VehicleLoanEntities.VehicleLoanDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.ManagerEntities.LoanAccount", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.ManagerEntities.LoanAccount", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.ManagerEntities.LoanOriginationWorkflow", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithMany()
                        .HasForeignKey("LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.Notification", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.NotificationPreference", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.EMIPlan", null)
                        .WithMany()
                        .HasForeignKey("EMIId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.PersonalLoanApplication", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanApplicationEntites.PersonalLoanApplication", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.Customer", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", b =>
                {
                    b.Navigation("AddressInformation")
                        .IsRequired();

                    b.Navigation("Applicants");

                    b.Navigation("Declaration")
                        .IsRequired();

                    b.Navigation("DocumentLinks");

                    b.Navigation("EmploymentDetails")
                        .IsRequired();

                    b.Navigation("FamilyEmergencyDetails")
                        .IsRequired();

                    b.Navigation("FinancialInformation")
                        .IsRequired();

                    b.Navigation("LoanDetails")
                        .IsRequired();

                    b.Navigation("PersonalDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.DocumentUpload", b =>
                {
                    b.Navigation("ApplicationLinks");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", b =>
                {
                    b.Navigation("BuilderInformation")
                        .IsRequired();

                    b.Navigation("HomeLoanDetails")
                        .IsRequired();

                    b.Navigation("PropertyDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", b =>
                {
                    b.Navigation("DealerInformation")
                        .IsRequired();

                    b.Navigation("VehicleInformation")
                        .IsRequired();

                    b.Navigation("VehicleLoanDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
