// <auto-generated />
using System;
using Kanini.LMP.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kanini.LMP.Data.Migrations
{
    [DbContext(typeof(LmpDbContext))]
    [Migration("20251208144055_UpdateDocumentStorage")]
    partial class UpdateDocumentStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AadhaarNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<decimal>("EligibilityScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("HomeOwnershipStatus")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PANNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte[]>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.EMIPlan", b =>
                {
                    b.Property<int>("EMIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMIId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyEMI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NextPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaidInstallments")
                        .HasColumnType("int");

                    b.Property<decimal>("PrincipleAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RateOfInterest")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalInterestPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRepaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EMIId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoanApplicationBaseId");

                    b.ToTable("EMIPlans");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", b =>
                {
                    b.Property<int>("LoanApplicationBaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanApplicationBaseId"));

                    b.Property<DateOnly?>("ApprovedDate")
                        .HasColumnType("date");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<byte[]>("DocumentData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoanProductType")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SubmissionDate")
                        .HasColumnType("date");

                    b.HasKey("LoanApplicationBaseId");

                    b.HasIndex("CustomerId");

                    b.ToTable("LoanApplicationBases", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.Faq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Faqs");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.AddressInformation", b =>
                {
                    b.Property<int>("AddressInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressInformationId"));

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber1")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MobileNumber2")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PresentAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AddressInformationId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("AddressInformations");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.Declaration", b =>
                {
                    b.Property<int>("DeclarationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeclarationId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("DeclarationId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("Declarations");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.FamilyEmergencyDetails", b =>
                {
                    b.Property<int>("FamilyEmergencyDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FamilyEmergencyDetailsId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<int>("MobileNumber")
                        .HasColumnType("int");

                    b.Property<string>("RelationshipWithApplicant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FamilyEmergencyDetailsId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("FamilyEmergencyDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.LoanDetails", b =>
                {
                    b.Property<int>("LoanDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanDetailsId"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MonthlyInstallment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("LoanDetailsId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.PersonalDetails", b =>
                {
                    b.Property<int>("PersonalDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalDetailsId"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DistrictOfBirth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EducationQualification")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<byte[]>("IDProofImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("LoanApplicationBaseId")
                        .HasColumnType("int");

                    b.Property<string>("PANNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ResidentialStatus")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<byte[]>("SignatureImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("PersonalDetailsId");

                    b.HasIndex("LoanApplicationBaseId")
                        .IsUnique();

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.LoanProduct", b =>
                {
                    b.Property<int>("LoanProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanProductId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoanType")
                        .HasColumnType("int");

                    b.HasKey("LoanProductId");

                    b.HasIndex("LoanType")
                        .IsUnique();

                    b.ToTable("LoanProducts");

                    b.HasData(
                        new
                        {
                            LoanProductId = 1,
                            IsActive = true,
                            LoanType = 1
                        },
                        new
                        {
                            LoanProductId = 2,
                            IsActive = true,
                            LoanType = 2
                        },
                        new
                        {
                            LoanProductId = 3,
                            IsActive = true,
                            LoanType = 3
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@gmail.com",
                            FullName = "Manager One",
                            PasswordHash = "$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYzOxJ6.Esi",
                            Roles = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", b =>
                {
                    b.HasBaseType("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanPurpose")
                        .HasColumnType("int");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("int");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("PropertyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.ToTable("HomeLoanApplications", (string)null);
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.PersonalLoanApplication", b =>
                {
                    b.HasBaseType("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<int>("LoanPurpose")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkExperienceYears")
                        .HasColumnType("int");

                    b.ToTable("PersonalLoanApplications", (string)null);
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", b =>
                {
                    b.HasBaseType("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanPurposeVehicle")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("OnRoadPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.ToTable("VehicleLoanApplications", (string)null);
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.Customer", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.CustomerEntities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.EMIPlan", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", "LoanApplicationBase")
                        .WithMany()
                        .HasForeignKey("LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LoanApplicationBase");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.Customer", "Customer")
                        .WithMany("LoanApplications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.AddressInformation", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", "LoanApplicationBase")
                        .WithOne("AddressInformation")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.AddressInformation", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanApplicationBase");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.Declaration", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", "LoanApplicationBase")
                        .WithOne("Declaration")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.Declaration", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanApplicationBase");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.FamilyEmergencyDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", "LoanApplicationBase")
                        .WithOne("FamilyEmergencyDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.FamilyEmergencyDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LoanApplicationBase");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.LoanDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", "LoanApplicationBase")
                        .WithOne("LoanDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.LoanDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanApplicationBase");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.PersonalDetails", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", "LoanApplicationBase")
                        .WithOne("PersonalDetails")
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanProductEntities.CommonLoanProductEntities.PersonalDetails", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanApplicationBase");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.Notification", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanini.LMP.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanApplicationEntites.HomeLoanApplication", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.PersonalLoanApplication", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanApplicationEntites.PersonalLoanApplication", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", b =>
                {
                    b.HasOne("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", null)
                        .WithOne()
                        .HasForeignKey("Kanini.LMP.Database.Entities.LoanApplicationEntites.VehicleLoanApplication", "LoanApplicationBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.Customer", b =>
                {
                    b.Navigation("LoanApplications");
                });

            modelBuilder.Entity("Kanini.LMP.Database.Entities.CustomerEntities.LoanApplicationBase", b =>
                {
                    b.Navigation("AddressInformation")
                        .IsRequired();

                    b.Navigation("Declaration")
                        .IsRequired();

                    b.Navigation("FamilyEmergencyDetails")
                        .IsRequired();

                    b.Navigation("LoanDetails")
                        .IsRequired();

                    b.Navigation("PersonalDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
