// SVG Images
export { default as OneBlue } from './images/1blue.svg';
export { default as TwoBlue } from './images/2blue.svg';
export { default as TwoGrey } from './images/2grey.svg';
export { default as ThreeBlue } from './images/3blue.svg';
export { default as ThreeGrey } from './images/3grey.svg';
export { default as FourBlue } from './images/4blue.svg';
export { default as FourGrey } from './images/4grey.svg';
export { default as FiveBlue } from './images/5blue.svg';
export { default as FiveGrey } from './images/5grey.svg';
export { default as SixBlue } from './images/6blue.svg';
export { default as SixGrey } from './images/6grey.svg';
export { default as Arrow } from './images/arrow.svg';
export { default as ArrowForm } from './images/ArrowForm.svg';
export { default as Bell } from './images/bell.svg';
export { default as Button } from './images/button.svg';
export { default as ChartEdit } from './images/Chart-Edit.svg';
export { default as CircleCheck } from './images/Circle-Check.svg';
export { default as ConsumerLoan } from './images/Consumer Loan.svg';
export { default as ConsumerLoanAlt } from './images/ConsumerLoan.svg';
export { default as CreditcardLoan } from './images/Creditcard Loan.svg';
export { default as CreditCardLoan } from './images/CreditCardLoan.svg';
export { default as CustomerDashboard } from './images/Customer Dashboard 1.svg';
export { default as Customer } from './images/Customer.svg';
export { default as Dashboard } from './images/Dashboard.svg';
export { default as DebitCard } from './images/debit-card 1.svg';
export { default as DebtConsolidationLoan } from './images/Debt Consolidation Loan.svg';
export { default as DebtConsolidationLoanAlt } from './images/DebtConsolidationLoan.svg';
export { default as Decision } from './images/Decision.svg';
export { default as Declaration } from './images/Declaration.svg';
export { default as DocumentVerificationI } from './images/DocumentverificationI.svg';
export { default as DocumentVerificationII } from './images/DocumentVerificationII.svg';
export { default as EducationLoan } from './images/Education Loan.svg';
export { default as Emi } from './images/Emi.svg';
export { default as Employment } from './images/Employment.svg';
export { default as FaqIcon } from './images/Faq.svg';
export { default as GreenTick } from './images/GreenTick.svg';
export { default as HousingLoan } from './images/Housing Loan.svg';
export { default as HousingLoanAlt } from './images/Housing-Loan.svg';
export { default as HousingLoanSecond } from './images/HousingLoan.svg';
export { default as KycEligibility } from './images/Kyceligibility.svg';
export { default as LoanAccelerator } from './images/LoanAccelerator.svg';
export { default as LoanAcceleratorLogo } from './images/LoanAcceleratorLogo.svg';
export { default as LoanApplied } from './images/LoanApplied.svg';
export { default as LoanDefault } from './images/Loandefault.svg';
export { default as LoanDetailsAndFinancial } from './images/LoanDetailsandFinancial.svg';
export { default as LogOut } from './images/Log-Out.svg';
export { default as Logo } from './images/logo.svg';
export { default as Logo1 } from './images/logo1.svg';
export { default as LogoN } from './images/LogoN.svg';
export { default as Manager } from './images/Manager.svg';
export { default as MedicalLoan } from './images/Medical Loan.svg';
export { default as NextButtonArrow } from './images/NextButtonArrow.svg';
export { default as Note } from './images/note.svg';
export { default as Notification } from './images/notification.svg';
export { default as NotificationBell } from './images/NotificationBell.svg';
export { default as OverallLoan } from './images/Overallloan.svg';
export { default as PersonalLoan } from './images/Personal Loan.svg';
export { default as PersonalLoanAlt } from './images/Personal-Loan.svg';
export { default as PersonalLoanSecond } from './images/PersonalLoan.svg';
export { default as Photo } from './images/photo.svg';
export { default as Query } from './images/query.svg';
export { default as Question1 } from './images/question1.svg';
export { default as Ray } from './images/Ray.svg';
export { default as Review } from './images/Review.svg';
export { default as Settings } from './images/Settings.svg';
export { default as SideMenuArrow } from './images/SideMenuArrow.svg';
export { default as SideMenuTriangle } from './images/SideMenuTriangle.svg';
export { default as SmallBusinessLoan } from './images/Small Business Loan.svg';
export { default as SmallBusinessLoanAlt } from './images/SmallBusiness-Loan.svg';
export { default as SmallBusinessLoanSecond } from './images/SmallBusinessLoan.svg';
export { default as Status } from './images/Status.svg';
export { default as Stroke } from './images/Stroke.svg';
export { default as TickMark } from './images/tickmark.svg';
export { default as Union } from './images/Union.svg';
export { default as Upload } from './images/Upload.svg';
export { default as UserIcon } from './images/UserIcon.svg';
export { default as VehicleLoanAlt } from './images/Vehicle-Loan.svg';
export { default as VehicleLoan } from './images/VehicleLoan.svg';
export { default as XMark } from './images/xmark.svg';

// PNG Images
export { default as Apply } from './images/apply.png';
export { default as Avatar } from './images/Avatar.png';
export { default as Back } from './images/back.png';
export { default as Chat } from './images/chat.png';
export { default as Ellipse5 } from './images/Ellipse 5.png';
export { default as Ellipse6 } from './images/Ellipse 6.png';
export { default as Faq } from './images/faq.png';
export { default as Forward } from './images/forward.png';
export { default as Group1500 } from './images/Group 1500.png';
export { default as Group2210 } from './images/Group 2210 (1).png';
export { default as Group48 } from './images/Group 48.png';
export { default as Group4898 } from './images/Group 4898.png';
export { default as Group5058 } from './images/Group 5058.png';
export { default as Option } from './images/option.png';
export { default as Paper } from './images/paper.png';
export { default as PdfLogo } from './images/pdflogo.png';
export { default as SettingsIcon } from './images/settings.png';
export { default as Tick } from './images/tick.png';
export { default as Union1 } from './images/union1.png';

// JPEG Images
export { default as AadharId } from './images/aadharid.jpeg';
export { default as Loancentric1 } from './images/Loancentric1.jpg';
export { default as Loancentric2 } from './images/Loancentric2.jpg';
export { default as Loancentric3 } from './images/Loancentric3.jpg';
export { default as Loancentric4 } from './images/Loancentric4.jpg';
export { default as Loancentric5 } from './images/Loancentric5.jpg';
export { default as Loancentric6 } from './images/Loancentric6.jpg';
export { default as Loancentric7 } from './images/Loancentric7.jpg';
export { default as Loancentric8 } from './images/Loancentric8.jpg';
export { default as Loancentric9 } from './images/Loancentric9.jpg';
export { default as NewPhoto } from './images/newphoto.jpg';
export { default as ProfileImage } from './images/profileimage.jpeg';
export { default as Signature } from './images/signature.jpeg';
export { default as Warning } from './images/Warning.jpg';

// React SVG
export { default as ReactLogo } from './react.svg';